[package]
name = "silent_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.3"
prost = "0.13.5"
tokio = { version = "1", features = ["full"] }
spinoff = "0.8.0"

[build-dependencies]
tonic-build = "0.12.3"
